// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoVJbUTIEKO4Q_gDALNRHslgWa_argKI',
    appId: '1:792942840141:android:e599ca49b496d172f00f04',
    messagingSenderId: '792942840141',
    projectId: 'learning-system-ee819',
    storageBucket: 'learning-system-ee819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCQxAUL3c34B5yNiYisaOcTdscNtojW-o',
    appId: '1:792942840141:ios:c039fe8a679b8497f00f04',
    messagingSenderId: '792942840141',
    projectId: 'learning-system-ee819',
    storageBucket: 'learning-system-ee819.appspot.com',
    androidClientId: '792942840141-4vnhclheiuaeahru1n416tv20u382td3.apps.googleusercontent.com',
    iosClientId: '792942840141-ql8rptfieh3462gs3f4so333hpkemu2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicTestingApp',
  );
}
